name: Deploy Jekyll site with Gulp

on:
  push:
    branches: [ main ]  # o la rama que uses como fuente

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7  # compatible con jekyll 3.9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # puedes ajustar esto si usas otra versión

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          yarn install

      - name: Build site with Gulp
        run: gulp

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
